import 'package:flutter/material.dart';

import '../../../../../core/design/design.dart';
import '../../../../../core/widgets/widgets.dart';
import '../../../../auth/domain/entities/app_role.dart';

/// The Sales Staff landing screen.
///
/// A **placeholder** for receipt capture — the reason this role opens the app,
/// and the first milestone's target end to end.
///
/// The capture control is rendered and **disabled**, rather than omitted. That
/// is the honest shape: the screen exists, the flow does not, and the button
/// cannot do anything because the `submit-receipt` Edge Function has not been
/// written. A working-looking button that silently did nothing would be worse
/// than an obviously inert one.
///
/// Three properties of the real flow that this screen must never quietly break
/// when it is implemented, all recorded in § 6 of the architecture
/// recommendation:
///
/// * The object path is generated by the **database**, never chosen by the
///   client.
/// * The SHA-256 duplicate guard must be computed over **the exact bytes
///   uploaded** — so downscale first, then hash.
/// * MIME type is decided by magic-byte sniffing **server-side**. Any check done
///   here is for a fast error message and is never the authority.
class SalesStaffSubmitPage extends StatelessWidget {
  const SalesStaffSubmitPage({super.key});

  @override
  Widget build(BuildContext context) {
    return SrPageBody(
      children: <Widget>[
        SrPageHeader(
          eyebrow: AppRole.salesStaff.displayName,
          title: 'Submit a receipt',
          description: 'Photograph a receipt for one of your assigned shops.',
        ),
        const SizedBox(height: SrSpacing.xxl),

        SrCard(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: <Widget>[
              const Center(
                child: SrIconDisc(
                  icon: Icons.photo_camera_outlined,
                  tone: SrTone.indigo,
                  size: 56,
                ),
              ),
              const SizedBox(height: SrSpacing.xl),
              Text(
                'Capture',
                style: SrTypography.cardTitle,
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: SrSpacing.sm),
              Text(
                'The camera flow is not built yet.',
                style: SrTypography.bodyMuted,
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: SrSpacing.xl),
              const SrButton(
                label: 'Take a photo',
                icon: Icons.photo_camera_rounded,
                fullWidth: true,
                // No handler: the upload path does not exist.
                onPressed: null,
              ),
              const SizedBox(height: SrSpacing.md),
              const SrButton(
                label: 'Choose from library',
                variant: SrButtonVariant.outline,
                icon: Icons.photo_library_outlined,
                fullWidth: true,
                onPressed: null,
              ),
            ],
          ),
        ),

        const SizedBox(height: SrSpacing.xxl),
        SrSectionCard(
          title: 'Assigned shops',
          description:
              'A receipt is always submitted against one of your assigned '
              'shops.',
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              const SrEmptyState(
                icon: Icons.storefront_outlined,
                title: 'No shops loaded',
                description:
                    'list_my_assigned_receipt_shops() is not called in this '
                    'build.',
              ),
              const SizedBox(height: SrSpacing.lg),
              const Wrap(
                spacing: SrSpacing.sm,
                runSpacing: SrSpacing.sm,
                children: <Widget>[
                  SrBadge(
                    label: 'Edge Function pending',
                    tone: SrTone.amber,
                    icon: Icons.schedule_rounded,
                  ),
                  SrBadge(label: 'Phase 1', tone: SrTone.indigo),
                ],
              ),
            ],
          ),
        ),
      ],
    );
  }
}
