import 'package:flutter/material.dart';

import '../../../../../core/design/design.dart';
import '../../../../../core/widgets/widgets.dart';
import '../../../../auth/domain/entities/portal_kind.dart';

/// The Sales Staff landing screen.
///
/// A **placeholder** for receipt capture — the reason this role opens the app,
/// and the first milestone's target end to end (§ 5.11).
///
/// It reproduces the web's tap-to-upload target from § 4.3: a large dashed
/// slate-300 area at the surface radius over a muted fill, with a 48px brand
/// disc and an upload glyph. On mobile that target should eventually offer
/// **camera capture and gallery pick**, which the handoff calls *"the single
/// biggest genuine mobile improvement available"* over the web's file input.
///
/// The controls are rendered and **disabled** rather than omitted. That is the
/// honest shape: the screen exists, the flow does not, and nothing can happen
/// because the `submit-receipt` Edge Function has not been written (SS-02 —
/// Storage has zero policies, so the upload needs the service key, which must
/// never reach a device). A working-looking button that silently did nothing
/// would be worse than an obviously inert one.
///
/// ## Three properties the real flow must not lose
///
/// * The object path is generated by the **database**; the client never chooses
///   it.
/// * The SHA-256 duplicate guard is computed over **the exact bytes uploaded** —
///   so downscale first, then hash. Hashing the original and uploading a resized
///   file silently defeats the guard.
/// * MIME type is decided by magic-byte sniffing **server-side**. Any check here
///   is for a fast error message and is never the authority.
///
/// And one thing that must never be rendered, here or anywhere: the storage
/// bucket, the object path, the file hash, any profile / membership /
/// organization id, or any failure code.
class SalesStaffSubmitPage extends StatelessWidget {
  const SalesStaffSubmitPage({super.key});

  @override
  Widget build(BuildContext context) {
    final SrColorScheme sr = context.sr;

    return SrPageBody(
      children: <Widget>[
        SrPageHeader(
          eyebrow: PortalKind.salesStaff.displayName,
          title: 'Submit a receipt',
          description: 'Photograph a receipt for one of your assigned shops.',
        ),
        const SizedBox(height: SrSpacing.xxl),

        // The web titles this card "Submit a receipt" under a "Receipts" page
        // header. Mobile promotes that to the page title when it splits the
        // page into Submit and History tabs, so the card takes a distinct name
        // rather than repeating it.
        SrSectionCard(
          title: 'Receipt details',
          description:
              'A receipt is always submitted against one of your assigned '
              'shops.',
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: <Widget>[
              // The web's shop <select>. Rendered as a disabled field, since
              // list_my_assigned_receipt_shops() is not called in this build.
              SrField(
                label: 'Shop',
                required: true,
                hint: 'Your assigned shops are not loaded in this build.',
                child: Container(
                  height: 44,
                  padding: const EdgeInsets.symmetric(
                    horizontal: SrSpacing.mdPlus,
                  ),
                  alignment: Alignment.centerLeft,
                  decoration: BoxDecoration(
                    color: sr.inputDisabledFill,
                    borderRadius: BorderRadius.circular(SrRadii.control),
                    border: Border.all(color: sr.inputBorder),
                  ),
                  child: Row(
                    children: <Widget>[
                      Expanded(
                        child: Text(
                          'Select a shop…',
                          style: SrTypography.body.copyWith(
                            color: sr.textMuted,
                          ),
                        ),
                      ),
                      Icon(
                        Icons.keyboard_arrow_down_rounded,
                        size: 16,
                        color: sr.textMuted,
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: SrSpacing.xl),
              const _UploadTarget(),
              const SizedBox(height: SrSpacing.xl),
              const SrButton(
                label: 'Submit receipt',
                size: SrButtonSize.lg,
                fullWidth: true,
                // No handler: the upload path does not exist.
                onPressed: null,
              ),
            ],
          ),
        ),

        const SizedBox(height: SrSpacing.xxl),
        SrSectionCard(
          title: 'Backend status',
          description:
              'What stands between this screen and a working submission.',
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              const Wrap(
                spacing: SrSpacing.sm,
                runSpacing: SrSpacing.sm,
                children: <Widget>[
                  SrBadge(
                    label: 'Edge Function pending',
                    tone: SrTone.amber,
                    icon: Icons.schedule_rounded,
                  ),
                  SrBadge(label: 'Phase 1', tone: SrTone.indigo),
                ],
              ),
              const SizedBox(height: SrSpacing.lg),
              Text(
                'Storage has zero policies, so an upload requires the service '
                'key — which must never reach a device. The submit-receipt '
                'Edge Function holds it server-side and is not built yet.',
                style: SrTypography.body.copyWith(color: sr.textSecondary),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

/// The dashed tap-to-upload target (§ 4.3).
class _UploadTarget extends StatelessWidget {
  const _UploadTarget();

  @override
  Widget build(BuildContext context) {
    return const Opacity(
      opacity: 0.7,
      child: SrEmptyState(
        icon: Icons.file_upload_outlined,
        tone: SrTone.indigo,
        title: 'Tap to upload a receipt',
        description:
            'JPEG, PNG or WebP, up to 10 MB. Camera capture is not built yet.',
      ),
    );
  }
}
